// Generated by tools/art/build_icons.py from tools/art/icons-manifest.json. Do not edit by hand:
// change the manifest (or assets/icons/custom/) and run `python3 tools/art/build_icons.py`.

import SwiftUI

/// Every content icon in the app: one case per meaning, drawn from the asset catalog folder `Icons`.
///
/// **One symbol, one meaning.** A glyph stands for exactly one idea across the whole app (a chair is
/// always "chair moves / a chair", a bell is always "reminders"), so she learns each picture once.
/// Need a new idea? Add a concept to the manifest with its own glyph; never reuse a case because it
/// "looks close". `AppIconTests` fails when two cases share a glyph outside `sharedGlyphs`.
///
/// Rules that come with it (`icon-va-chong-nham-chan.md` §2, `nguon-icon.md` §4): an icon always sits
/// next to its text label and is hidden from VoiceOver (the label carries the meaning); it sits on the
/// watercolour wash chip; `image` (Phosphor Bold or a custom glyph of the same weight) is the normal
/// state, `selectedImage` (Fill) the selected one. System controls (chevron, checkmark, xmark, plus,
/// play/pause) stay SF Symbols. Glyph colour comes from the case's `tint` role, never sky or sun as
/// a stroke colour.
///
/// Sources: Phosphor Icons 2.1.1 (MIT, `Resources/Licenses/Phosphor-MIT.txt`) and
/// custom glyphs in `assets/icons/custom/`. The raw value is the image set name inside `Icons/`.
enum AppIcon: String, CaseIterable, Sendable {
    /// Walk session; walking in general (goal "Lose some weight", gentle restart, week calendar). Phosphor
    /// `person-simple-walk`, tint sap. Replaces SF `figure.walk`.
    case walk
    /// Long walk; longest walk without a break. Phosphor `person-simple-hike`, tint sap. Replaces SF
    /// `figure.walk.motion`.
    case longWalk = "long-walk"
    /// Chair moves; a chair (goal "Up from chairs", sturdy chair, sit-to-stand). Phosphor `chair`, tint sap.
    /// Replaces SF `chair.fill`.
    case chair
    /// Seated level ("Starts seated"). Phosphor `armchair`, tint sap. Replaces SF `figure.seated.side`.
    case seated
    /// Stretch session. Custom `stretch`, tint sky. Replaces SF `figure.flexibility`.
    case stretch
    /// Balance: Steady set, goal "Steadier feet", hands on the chair. Phosphor `person-simple-tai-chi`, tint
    /// sky. Replaces SF `figure.stand`.
    case balance
    /// Outdoor walk; location (permission, "Use my location"). Phosphor `map-pin`, tint sky. Replaces SF
    /// `location.fill`.
    case outdoors
    /// Journeys, postcards, miles on the route. Phosphor `map-trifold`, tint sky. Replaces SF `map.fill`.
    case journey
    /// Active days; the tree growing (Sapling). Phosphor `leaf`, tint sap. Replaces SF `leaf.fill`.
    case activeDay = "active-day"
    /// Tree stage: Sprout. Phosphor `plant`, tint sap. Replaces SF `leaf`.
    case sprout
    /// Tree stage: Seed. Phosphor `circle-dashed`, tint sap. Replaces SF `circle.dotted`.
    case seed
    /// Tree stage: Tree. Phosphor `tree`, tint sap. Replaces SF `tree.fill`.
    case tree
    /// Progress; weekly recap. Phosphor `chart-bar`, tint sap. Replaces SF `chart.bar.fill`.
    case progress
    /// All-day steps; "Just count my steps"; feet flat. Phosphor `footprints`, tint sap. Replaces SF
    /// `shoeprints.fill`.
    case steps
    /// Everyday wins. Phosphor `thumbs-up`, tint sap. Replaces SF `checkmark.circle.fill`.
    case everydayWins = "everyday-wins"
    /// Time: "Pick a time", minutes moving. Phosphor `clock`, tint ochre. Replaces SF `clock.fill`.
    case time
    /// The 12-week program; your week; your plan. Phosphor `calendar-dots`, tint sap. Replaces SF `calendar`.
    case program
    /// 2-week self-check; self-check reminders. Phosphor `timer`, tint ochre. Replaces SF `stopwatch.fill`.
    case selfCheck = "self-check"
    /// New this week; goal "Not sure yet". Phosphor `sparkle`, tint ochre. Replaces SF `sparkles`.
    case new
    /// Moved up a level; a new personal record. Phosphor `arrow-circle-up`, tint sap. Replaces SF
    /// `arrow.up.circle.fill`.
    case levelUp = "level-up"
    /// Shorter today; moved down a level. Phosphor `arrow-circle-down`, tint sap. Replaces SF
    /// `arrow.down.circle.fill`.
    case levelDown = "level-down"
    /// Rest day. Phosphor `moon-stars`, tint sap. Replaces SF `moon.zzz.fill`.
    case rest
    /// Done for today. Phosphor `seal-check`, tint sap. Replaces SF `checkmark.seal.fill`.
    case done
    /// Countdown before a session ("3, 2, 1"). Phosphor `hourglass-simple`, tint sap. Replaces SF `timer`.
    case countdown
    /// Goal "Less pain" (not the heart: that is Apple Health). Phosphor `hand-heart`, tint danger. Replaces SF
    /// `heart`.
    case lessPain = "less-pain"
    /// Goal "More energy". Phosphor `sun`, tint ochre. Replaces SF `sun.max.fill`.
    case energy
    /// Goal "Keep up with grandkids". Custom `grandkids`, tint sienna. Replaces SF
    /// `figure.2.and.child.holdinghands`.
    case grandkids
    /// Barrier "My joints hurt" (user test decides; fallback: no icon). Phosphor `bandaids`, tint danger.
    /// Replaces SF `bandage.fill`.
    case jointsHurt = "joints-hurt"
    /// Barrier "Videos go too fast". Phosphor `fast-forward`, tint sky. Replaces SF `forward.fill`.
    case videosFast = "videos-fast"
    /// Barrier "No time for me" (caring for others). Phosphor `users`, tint sienna. Replaces SF
    /// `person.2.fill`.
    case busy
    /// Barrier "I got bored". Phosphor `smiley-meh`, tint ochre. Replaces SF `zzz`.
    case bored
    /// Subscription, trial ending, billing, "Surprise charges". Phosphor `credit-card`, tint sap. Replaces SF
    /// `creditcard.fill`.
    case payment
    /// Paywall timeline "Today: full access". Phosphor `lock-open`, tint sap. Replaces SF `lock.open.fill`.
    case unlock
    /// Pro / locked content. Phosphor `lock`, tint sap. Replaces SF `lock.fill`.
    case pro
    /// Reminder moment "After my morning coffee". Phosphor `coffee`, tint ochre. Replaces SF
    /// `cup.and.saucer.fill`.
    case coffee
    /// Reminder moment "After lunch". Phosphor `fork-knife`, tint ochre. Replaces SF `fork.knife`.
    case lunch
    /// Reminder moment "During evening TV". Phosphor `television-simple`, tint ochre. Replaces SF `tv.fill`.
    case eveningTV = "evening-tv"
    /// Reminders and notifications. Phosphor `bell`, tint sap. Replaces SF `bell.fill`.
    case reminder
    /// Notification setting "New journeys". Phosphor `newspaper`, tint sap. Replaces SF `newspaper.fill`.
    case newJourneys = "new-journeys"
    /// Language and units. Phosphor `globe-simple`, tint sap. Replaces SF `globe`.
    case language
    /// Text size. Phosphor `text-aa`, tint sap. Replaces SF `textformat.size`.
    case textSize = "text-size"
    /// Appearance (light / dark). Phosphor `circle-half`, tint sap. Replaces SF `circle.lefthalf.filled`.
    case appearance
    /// Me: "Your body"; self-check arms step. Phosphor `person-arms-spread`, tint sap. Replaces SF
    /// `figure.arms.open`.
    case yourBody = "your-body"
    /// Sound. Phosphor `speaker-high`, tint sap. Replaces SF `speaker.wave.2.fill`.
    case sound
    /// Coach voice; voice louder than music. Phosphor `user-sound`, tint sap. Replaces SF `person.wave.2.fill`.
    case coachVoice = "coach-voice"
    /// Music. Phosphor `music-note`, tint sap. Replaces SF `music.note`.
    case music
    /// Captions. Phosphor `closed-captioning`, tint sap. Replaces SF `captions.bubble.fill`.
    case captions
    /// Voice-led sessions; "One ear free to hear traffic". Phosphor `ear`, tint sap. Replaces SF `ear.fill`.
    case listen
    /// Apple Health. Phosphor `heart`, tint danger. Replaces SF `heart.fill`.
    case health
    /// "This hurts" / stop / pain alert. Phosphor `hand-palm`, tint danger. Replaces SF `hand.raised.fill`.
    case hurts
    /// Safety warning; "Stop if it hurts". Phosphor `warning`, tint danger. Replaces SF
    /// `exclamationmark.triangle.fill`.
    case warning
    /// Help; barrier "Didn't know where to start". Phosphor `question`, tint sap. Replaces SF
    /// `questionmark.circle.fill`.
    case help
    /// Contact us. Phosphor `envelope-simple`, tint sap. Replaces SF `envelope.fill`.
    case contact
    /// Terms of Use. Phosphor `file-text`, tint sap. Replaces SF `doc.text.fill`.
    case terms
    /// Privacy. Phosphor `shield-check`, tint sap. Replaces SF `lock.shield.fill`.
    case privacy
    /// Acknowledgements: the licences of the icon set and other credits (Me → Help). Phosphor `book-open-text`,
    /// tint sap.
    case acknowledgements
    /// Restore purchase. Phosphor `arrow-clockwise`, tint sap. Replaces SF `arrow.clockwise`.
    case restore
    /// Delete all my data. Phosphor `trash`, tint danger. Replaces SF `trash.fill`.
    case deleteData = "delete-data"
    /// Note ("isn't medical advice"). Phosphor `info`, tint sap. Replaces SF `info.circle`.
    case info
    /// Water with you. Phosphor `drop`, tint sky. Replaces SF `waterbottle.fill`.
    case water
    /// Sturdy shoes. Phosphor `sneaker`, tint sap. Replaces SF `shoe.fill`.
    case shoes
    /// Phone charged. Phosphor `battery-full`, tint sap. Replaces SF `battery.100percent`.
    case phoneCharged = "phone-charged"
    /// Hot-day tip. Phosphor `thermometer-hot`, tint ochre. Replaces SF `thermometer.sun.fill`.
    case hotDay = "hot-day"
    /// Motion: phone held to the chest / on the table. Phosphor `device-mobile`, tint sap. Replaces SF
    /// `iphone.gen3.radiowaves.left.and.right`.
    case motion
    /// Sore spot: Knees. Custom `body-knees`, tint sienna.
    case bodyKnees = "body-knees"
    /// Sore spot: Hips. Custom `body-hips`, tint sienna.
    case bodyHips = "body-hips"
    /// Sore spot: Lower back. Custom `body-lower-back`, tint sienna.
    case bodyLowerBack = "body-lower-back"
    /// Sore spot: Shoulders. Custom `body-shoulders`, tint sienna.
    case bodyShoulders = "body-shoulders"
    /// Sore spot: Joint replacement. Custom `body-joint-replacement`, tint sienna.
    case bodyJointReplacement = "body-joint-replacement"
    /// Limit: "Can't get down on the floor". Custom `limit-floor`, tint sienna.
    case limitFloor = "limit-floor"
    /// Limit: "Standing long is hard". Custom `limit-standing-long`, tint sienna.
    case limitStandingLong = "limit-standing-long"
    /// Limit: "Dizzy". Custom `limit-dizzy`, tint sienna.
    case limitDizzy = "limit-dizzy"
    /// Limit: "Unsteady". Custom `limit-unsteady`, tint sienna.
    case limitUnsteady = "limit-unsteady"
    /// Limit: "No jumping". Custom `limit-no-jumping`, tint sienna.
    case limitNoJumping = "limit-no-jumping"

    /// Colour role of the glyph (and its wash). Mapped to Palette colours by the view layer.
    enum Tint: String, Sendable {
        case sap, sky, ochre, sienna, danger
    }

    /// Namespaced asset catalog folder holding every icon.
    static let folder = "Icons"

    /// Catalog name of the normal-state image (Bold).
    var assetName: String { "\(Self.folder)/\(rawValue)" }

    /// Catalog name of the selected-state image (Fill).
    var selectedAssetName: String { "\(Self.folder)/\(rawValue)-fill" }

    /// Normal state, as a template so `foregroundStyle` colours it.
    var image: Image { Image(assetName).renderingMode(.template) }

    /// Selected state (Fill twin of the same glyph), as a template.
    var selectedImage: Image { Image(selectedAssetName).renderingMode(.template) }

    /// `selectedImage` when selected, otherwise `image`.
    func image(selected: Bool) -> Image { selected ? selectedImage : image }

    /// The two images of a two-tone icon: the figure and the meaning mark drawn over it.
    enum Layer: String, Sendable {
        case base, mark
    }

    /// Catalog name of one layer of a two-tone icon, or nil for one-colour icons. The base has a Fill
    /// twin for the selected state (solid head); the mark is the same in both states.
    func layerAssetName(_ layer: Layer, selected: Bool = false) -> String? {
        guard isLayered else { return nil }
        return switch layer {
        case .base: "\(Self.folder)/\(rawValue)-base\(selected ? "-fill" : "")"
        case .mark: "\(Self.folder)/\(rawValue)-mark"
        }
    }

    /// Source glyph, `phosphor:<name>` or `custom:<name>`: two cases with the same glyph would mean
    /// one picture carrying two meanings.
    var glyph: String {
        switch self {
        case .walk: "phosphor:person-simple-walk"
        case .longWalk: "phosphor:person-simple-hike"
        case .chair: "phosphor:chair"
        case .seated: "phosphor:armchair"
        case .stretch: "custom:stretch"
        case .balance: "phosphor:person-simple-tai-chi"
        case .outdoors: "phosphor:map-pin"
        case .journey: "phosphor:map-trifold"
        case .activeDay: "phosphor:leaf"
        case .sprout: "phosphor:plant"
        case .seed: "phosphor:circle-dashed"
        case .tree: "phosphor:tree"
        case .progress: "phosphor:chart-bar"
        case .steps: "phosphor:footprints"
        case .everydayWins: "phosphor:thumbs-up"
        case .time: "phosphor:clock"
        case .program: "phosphor:calendar-dots"
        case .selfCheck: "phosphor:timer"
        case .new: "phosphor:sparkle"
        case .levelUp: "phosphor:arrow-circle-up"
        case .levelDown: "phosphor:arrow-circle-down"
        case .rest: "phosphor:moon-stars"
        case .done: "phosphor:seal-check"
        case .countdown: "phosphor:hourglass-simple"
        case .lessPain: "phosphor:hand-heart"
        case .energy: "phosphor:sun"
        case .grandkids: "custom:grandkids"
        case .jointsHurt: "phosphor:bandaids"
        case .videosFast: "phosphor:fast-forward"
        case .busy: "phosphor:users"
        case .bored: "phosphor:smiley-meh"
        case .payment: "phosphor:credit-card"
        case .unlock: "phosphor:lock-open"
        case .pro: "phosphor:lock"
        case .coffee: "phosphor:coffee"
        case .lunch: "phosphor:fork-knife"
        case .eveningTV: "phosphor:television-simple"
        case .reminder: "phosphor:bell"
        case .newJourneys: "phosphor:newspaper"
        case .language: "phosphor:globe-simple"
        case .textSize: "phosphor:text-aa"
        case .appearance: "phosphor:circle-half"
        case .yourBody: "phosphor:person-arms-spread"
        case .sound: "phosphor:speaker-high"
        case .coachVoice: "phosphor:user-sound"
        case .music: "phosphor:music-note"
        case .captions: "phosphor:closed-captioning"
        case .listen: "phosphor:ear"
        case .health: "phosphor:heart"
        case .hurts: "phosphor:hand-palm"
        case .warning: "phosphor:warning"
        case .help: "phosphor:question"
        case .contact: "phosphor:envelope-simple"
        case .terms: "phosphor:file-text"
        case .privacy: "phosphor:shield-check"
        case .acknowledgements: "phosphor:book-open-text"
        case .restore: "phosphor:arrow-clockwise"
        case .deleteData: "phosphor:trash"
        case .info: "phosphor:info"
        case .water: "phosphor:drop"
        case .shoes: "phosphor:sneaker"
        case .phoneCharged: "phosphor:battery-full"
        case .hotDay: "phosphor:thermometer-hot"
        case .motion: "phosphor:device-mobile"
        case .bodyKnees: "custom:body-knees"
        case .bodyHips: "custom:body-hips"
        case .bodyLowerBack: "custom:body-lower-back"
        case .bodyShoulders: "custom:body-shoulders"
        case .bodyJointReplacement: "custom:body-joint-replacement"
        case .limitFloor: "custom:limit-floor"
        case .limitStandingLong: "custom:limit-standing-long"
        case .limitDizzy: "custom:limit-dizzy"
        case .limitUnsteady: "custom:limit-unsteady"
        case .limitNoJumping: "custom:limit-no-jumping"
        }
    }

    /// Two-tone icons (body regions and limitations): show them with `LayeredIcon`; their `image` is
    /// only a single-colour fallback.
    var isLayered: Bool {
        switch self {
        case .bodyKnees, .bodyHips, .bodyLowerBack, .bodyShoulders, .bodyJointReplacement, .limitFloor,
             .limitStandingLong, .limitDizzy, .limitUnsteady, .limitNoJumping: true
        default: false
        }
    }

    /// Colour role of this icon (`icon-va-chong-nham-chan.md`, icon vocabulary).
    var tint: Tint {
        switch self {
        case .walk, .longWalk, .chair, .seated, .activeDay, .sprout, .seed, .tree, .progress, .steps, .everydayWins,
             .program, .levelUp, .levelDown, .rest, .done, .countdown, .payment, .unlock, .pro, .reminder,
             .newJourneys, .language, .textSize, .appearance, .yourBody, .sound, .coachVoice, .music, .captions,
             .listen, .help, .contact, .terms, .privacy, .acknowledgements, .restore, .info, .shoes, .phoneCharged,
             .motion: .sap
        case .stretch, .balance, .outdoors, .journey, .videosFast, .water: .sky
        case .time, .selfCheck, .new, .energy, .bored, .coffee, .lunch, .eveningTV, .hotDay: .ochre
        case .grandkids, .busy, .bodyKnees, .bodyHips, .bodyLowerBack, .bodyShoulders, .bodyJointReplacement,
             .limitFloor, .limitStandingLong, .limitDizzy, .limitUnsteady, .limitNoJumping: .sienna
        case .lessPain, .jointsHurt, .health, .hurts, .warning, .deleteData: .danger
        }
    }

    /// Glyphs deliberately shared by several concepts (`sharedGlyphs` in the manifest).
    static let sharedGlyphs: [String: Set<AppIcon>] = [:]
}

/// Draws an `AppIcon` in two colours, like the Claude Design sore-spot mock: the figure (`base` layer,
/// usually ink at about 55 %) and the meaning mark (`mark` layer: the sore spot, the clock, the swirl,
/// the "no" badge) in solid sienna, stacked from two template images so each takes its own colour.
/// Use it for the body and limitation icons, which do not read in one colour at 20 pt, e.g.
/// `LayeredIcon(icon: .bodyKnees, baseColor: Palette.text.opacity(0.55), markColor: Palette.accent)`.
/// A one-colour icon renders whole in `markColor`. The view fills its frame (`scaledToFit`): size it
/// with `.frame`. Decorative: hidden from VoiceOver, the text label beside it carries the meaning.
struct LayeredIcon: View {
    let icon: AppIcon
    let baseColor: Color
    let markColor: Color
    var selected = false

    var body: some View {
        ZStack {
            if let base = icon.layerAssetName(.base, selected: selected), let mark = icon.layerAssetName(.mark) {
                layer(base).foregroundStyle(baseColor)
                layer(mark).foregroundStyle(markColor)
            } else {
                layer(selected ? icon.selectedAssetName : icon.assetName).foregroundStyle(markColor)
            }
        }
        .accessibilityHidden(true)
    }

    private func layer(_ name: String) -> some View {
        Image(name).renderingMode(.template).resizable().scaledToFit()
    }
}
