import Foundation
import GentleWalkCore

/// Loads the bundled content JSON (App/Resources/Content, generated by tools/content/build_content.py)
/// into one `ContentBundle`. Called once at launch; the result is checked with `ContentValidator`.
enum ContentStore {
    enum LoadError: Error, Equatable {
        case missingFile(String)
        case schemaMismatch(file: String, found: Int, expected: Int)
    }

    static func load(bundle: Bundle) throws -> ContentBundle {
        let voice: VoiceFile = try decode("voice-lines", from: bundle)
        let exercises: ExerciseFile = try decode("exercises", from: bundle)
        let journeys: JourneyFile = try decode("journeys", from: bundle)
        let sessions: SessionFile = try decode("sessions", from: bundle)
        return ContentBundle(
            exercises: exercises.exercises,
            journeys: journeys.journeys,
            voiceLines: voice.voiceLines,
            sessions: sessions.sessions
        )
    }

    private static func decode<File: Decodable & Versioned>(_ name: String, from bundle: Bundle) throws -> File {
        guard let url = bundle.url(forResource: name, withExtension: "json") else {
            throw LoadError.missingFile("\(name).json")
        }
        let file = try JSONDecoder().decode(File.self, from: Data(contentsOf: url))
        guard file.schemaVersion == CoreInfo.contentSchemaVersion else {
            throw LoadError.schemaMismatch(file: name, found: file.schemaVersion, expected: CoreInfo.contentSchemaVersion)
        }
        return file
    }
}

private protocol Versioned { var schemaVersion: Int { get } }
private struct VoiceFile: Decodable, Versioned { var schemaVersion: Int; var voiceLines: [VoiceLine] }
private struct ExerciseFile: Decodable, Versioned { var schemaVersion: Int; var exercises: [Exercise] }
private struct JourneyFile: Decodable, Versioned { var schemaVersion: Int; var journeys: [Journey] }
private struct SessionFile: Decodable, Versioned { var schemaVersion: Int; var sessions: [SessionTemplate] }
